filtering by name and price
cesarFuhr/books-service pull request #15
Opened 2023-08-13 02:15 UTC by ramon-reichert

I did not touch database_test.go yet. I'll do it if you aprove what I've done until now.

2023-08-14 13:39 UTC, cesarFuhr requested changes
After these changes please add tests.
We will improve it more after the tests are written, this a good development flow:
1 - Make it work
2 - Write the tests to make sure its working as expected
3 - Refactor the code to make it easier to read/faster

2023-08-14 13:39 UTC, cesarFuhr commented on cmd/api/main.go
> +	err := r.ParseForm() //Verify errors in request query params and populates r.Form with its values.
This should be used for other types of requests (the ones with the `x-www-form-urlencoded` application type header).
Please use `r.URL.Query()`, it the correct one for this case https://pkg.go.dev/net/url#example-URL.Query.

2023-08-14 13:39 UTC, cesarFuhr commented on cmd/api/main.go
> +	err := r.ParseForm() //Verify errors in request query params and populates r.Form with its values.
https://go.dev/play/p/HOCbBF8c9UI

2023-08-14 13:39 UTC, cesarFuhr commented on cmd/api/main.go
> +		name = "%"
This is leaking SQL logic into the request handling layer.
Its better to pass the empty string to the database function and let it decide what that should be in the SQL statement.

2023-08-14 13:39 UTC, cesarFuhr commented on cmd/api/main.go
> +			w.WriteHeader(http.StatusInternalServerError)
This is probably a user error, if the user passes an invalid float string this error would occur.

2023-08-14 13:39 UTC, cesarFuhr commented on cmd/api/main.go
> +			w.WriteHeader(http.StatusInternalServerError)
Same here.

2023-08-19 16:54 UTC, ramon-reichert commented
Sorry, I've forgotten to write the test filtering by price. I'll do it now.

2023-08-19 18:32 UTC, cesarFuhr approved these changes
Other than those little changes, LGTM.

2023-08-19 18:32 UTC, cesarFuhr commented on cmd/api/database_test.go
> +		is.Equal(returnedBooks[:], testBookslist[0:6])
```suggestion
		is.Equal(returnedBooks, testBookslist[0:6])

2023-08-19 18:32 UTC, cesarFuhr commented on cmd/api/database_test.go
> +		is.Equal(returnedBooks[:], testBookslist[5:11])
```suggestion
		is.Equal(returnedBooks, testBookslist[5:11])

2023-08-19 18:32 UTC, cesarFuhr commented on cmd/api/database_test.go
>  		}
All the following tests depend on this `for` loop that creates the books to be listed.
This means that the other tests depend on this test to run correctly, lets move this `for` loop to line `111`, that way you set up all the tests in one spot, outside of the `t.Run` function.

2023-08-19 19:06 UTC, cesarFuhr reviewed
There is only one last test missing, filter by name with partial match.

Lets say you have a book called `Book of Frogs` in the database. If you filter the search based on `name`, with the filter value `Frog`, this book should be returned.

2023-08-21 11:19 UTC, merged